data:
  name: external_dataset #calibration_dataset # aachen_dataset # kaggle_rotation_dataset # calibration_dataset # ransac_dataset # 
  data_dir: data7/
  train_split: split/train_data7.txt
  val_split: split/val_data7.txt
  test_split: split/test_data7.txt
  num_workers: 24
  seed: 1
  train_batch_size: 32
  val_batch_size: 1
  test_batch_size: 1
  batch_size: 1
  transform_idx: #0 #14 #14 # idx 0-14
  augment: true
model:
  name: densenet # convnext
  model: densenet161 # convnext_tiny
  heads: # Options: roll, rho, fov, dist
  - roll
  - rho
  - fov
  - k1_hat
  normalize_features: true
  duplicate_optimizer_per_scale: true
  normalize_dt: false
  loss: NLL # L1, L2, Huber, NLL
  num_bins: 256
train:
  seed: 0
  load_experiment: #None #train_roll_data3
  epochs: 12 # Keep this to about 7 for full training.
  log_every_iter: 20
  eval_every_iter: 3000 # keep this to about 3-5 times per epoch.
  lr: 1.0e-04
  clip_grad: 1.0
  median_metrics:
  - loss/total # this loss is computed directly on the outputs of the networks
#   - roll/L1_degree_loss
#   - rho/L1_pitch_degree_loss
#   - fov/L1_degree_loss
  q90_metrics:
  - loss/total
#   - roll/L1_degree_loss
#   - rho/L1_pitch_degree_loss
#   - fov/L1_degree_loss
  
  
