data:
  name: external_dataset
  data_dir:
  num_workers: 4
  seed: 1
  val_batch_size: 1
  test_batch_size: 1
  batch_size: 1
  augment: true
model:
  name: densenet # convnext
  model: densenet161 # convnext_tiny
  heads:
  - roll
  - rho
  - fov
  - k1_hat
  normalize_features: true
  duplicate_optimizer_per_scale: true
  normalize_dt: false
  loss: NLL # L1, L2, Huber, NLL
  num_bins: 256
  
  
